# Main Application Configuration
spring:
  threads:
    virtual:
      enabled: true

  # Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # Application configuration
  application:
    name: elasticsearch-reactive-service

  # Spring Data Elasticsearch reactive client configuration
  elasticsearch:
    # Use explicit URIs if provided, otherwise build from app.elasticsearch.*
    uris: ${SPRING_ELASTICSEARCH_URIS:${app.elasticsearch.scheme}://${app.elasticsearch.host}:${app.elasticsearch.port}}
    username: ${SPRING_ELASTICSEARCH_USERNAME:${app.elasticsearch.username}}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:${app.elasticsearch.password}}
  main:
    web-application-type: reactive 
  boot:
    admin:
      client:
        enabled: ${SPRING_BOOT_ADMIN_ENABLED:false}
        url: ${SPRING_BOOT_ADMIN_URL:}
        # optional credentials if your Admin server is secured
        username: ${SPRING_BOOT_ADMIN_USERNAME:}
        password: ${SPRING_BOOT_ADMIN_PASSWORD:}
        instance:
          name: ${SPRING_APPLICATION_NAME:${spring.application.name}}
          # if the service runs behind a proxy or in Docker, set a reachable URL
          service-base-url: ${SPRING_BOOT_ADMIN_INSTANCE_URL:}

server:
  port: 8080

# Custom Elasticsearch configuration
app:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST:192.168.1.27}
    port: ${ELASTICSEARCH_PORT:9200}
    scheme: ${ELASTICSEARCH_SCHEME:http}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    
    # Default search configuration
    default-page-size: 20
    max-page-size: 100
    default-timeout: 30s
    
    # Virtual thread pool configuration
    virtual-threads:
      enabled: true
      core-pool-size: 10
      max-pool-size: 1000
      
    # Reactive configuration
    reactive:
      buffer-size: 1000
      prefetch: 256

# Logging configuration
logging:
  level:
    com.microservices.elasticsearch.dynamic.query: INFO
    co.elastic.clients: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI/Swagger configuration (springdoc)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Management endpoints (for monitoring)

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
      
app:
  elasticsearch:
    host: 192.168.1.27
    port: 9200
    scheme: http
    
logging:
  level:
    root: INFO
    com.microservices.elasticsearch.dynamic.query: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
      
app:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT:9200}
    scheme: ${ELASTICSEARCH_SCHEME:https}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    
logging:
  level:
    root: WARN
    com.microservices.elasticsearch.dynamic.query: INFO

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
      
app:
  elasticsearch:
    host: localhost
    port: 9201
    scheme: http
    
logging:
  level:
    root: ERROR
    com.microservices.elasticsearch.dynamic.query: DEBUG
